{% set version = "13.0.1" %}
{% set llvm_version = "15" %}

package:
  name: metal-llvm-tools-{{ llvm_version }}
  version: {{ version }}

source:
  # See https://github.com/JuliaPackaging/Yggdrasil/blob/master/M/Metal_LLVM_Tools/build_tarballs.jl#L18
  # for the commits
  url: https://github.com/JuliaGPU/llvm-metal/archive/b7f9ec094a19439c59e4095d3c92e506eb6c1285.tar.gz
  sha256: 4f2f879fe77e8dd8f6c388767b61ecee9bfa916644be45e461f47b3c6e5995ff

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - python >=3
  host:
    - zlib

test:
  commands:
    - test -f ${PREFIX}/bin/metallib-as-{{ llvm_version }}

about:
  home: https://github.com/JuliaGPU/llvm-metal
  dev_url: https://github.com/JuliaGPU/llvm-metal
  license: MIT AND Apache-2.0 WITH LLVM-exception
  license_file:
    - llvm/LICENSE.TXT
    - third-party.txt
  license_family: Apache
  summary: LLVM IR assembler and disassembler for metal

extra:
  recipe-maintainers:
    - isuruf
  feedstock-name: metal-llvm-tools
